language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=1.4.1
  - MRUBY_VERSION=master
matrix:
  allow_failures:
    - env: MRUBY_VERSION=master
branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf libonig-dev
  - gem install rubocop --no-document

script:
  - rubocop
  - rake test
